// <auto-generated />
using EFCoreJoinTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreJoinTest.Migrations
{
    [DbContext(typeof(CaseStudyContext))]
    partial class CaseStudyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreJoinTest.CaseStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaseStudyName");

                    b.HasKey("Id");

                    b.HasIndex("CaseStudyName")
                        .IsUnique()
                        .HasFilter("[CaseStudyName] IS NOT NULL");

                    b.ToTable("CaseStudy");
                });

            modelBuilder.Entity("EFCoreJoinTest.CommonData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaseStudyId");

                    b.Property<string>("CommonText");

                    b.HasKey("Id");

                    b.HasIndex("CaseStudyId");

                    b.ToTable("CommonData");
                });

            modelBuilder.Entity("EFCoreJoinTest.V1Extended", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommonDataId");

                    b.Property<string>("ExtendedData");

                    b.HasKey("Id");

                    b.HasIndex("CommonDataId");

                    b.ToTable("V1Extended");
                });

            modelBuilder.Entity("EFCoreJoinTest.CommonData", b =>
                {
                    b.HasOne("EFCoreJoinTest.CaseStudy", "CaseStudy")
                        .WithMany()
                        .HasForeignKey("CaseStudyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFCoreJoinTest.V1Extended", b =>
                {
                    b.HasOne("EFCoreJoinTest.CommonData", "CommonData")
                        .WithMany()
                        .HasForeignKey("CommonDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
